config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Control Panel
  # # ================================================================================================ #
  # namespace :control_panel, path: 'control_panel' do
  #   get '/channels', to: 'channels#show', as: 'control_panel'
  #   namespace :channels do
  #     post '/suspension', to: 'suspensions#create'
  #   end
  # end
  # # ================================================================================================ #

  # # Channel
  # # ================================================================================================ #
  # namespace :channels, path: 'channels/channel_id=:channel_id' do
  #   get '/', to: 'channels#show', as: 'show_channel'
  #   get '/edit', to: 'channels#edit', as: 'edit_channel'
  #   patch '/update', to: 'channels#update', as: 'channel'
  # end
  # # ================================================================================================ #

  # # Sites
  # # ================================================================================================ #
  # namespace :sites do
  #   post '/', to: 'sites#create'
  # end
  # # ================================================================================================ #
  
  # #Sites Setup
  # # ================================================================================================ #
  # namespace :sites_setup, path: 'sites/site=:site_id' do
  #   get '/edit', to: 'details#edit'
  #   namespace :accounts, path: 'account' do
  #     get '/create', to: 'users#create'
  #     post '/new', to: 'users#new'
  #   end
  # end
  # # ================================================================================================ #

  match 'pubsubhubbub/post', to: 'youtube_webhook_verifications#create', via: [:get, :post]

  namespace :control_panel, path: 'controlpanel' do
    resources :channels, only: :show do
      resource :suspension, only: :create, module: :channels
    end
    resources :videos, only: [:show, :edit, :update]
  end

  namespace :sites_setup, path: 'sites/:site_id/welcome' do
    resource :details, only: [:edit, :update], path: 'your-site'
    resource :users, only: [:new, :create], path: 'account'
  end

  resources :sites, only: [:create, :show]
  resources :channels, only: [:show, :edit, :update]
  resources :notification_subscriptions, only: [:create]
  delete :notification_subscriptions, to: 'notification_subscriptions#destroy'

  root 'static#home_page'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sundaeclub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.typekit.net/mlt3byj.css">

    <%#= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= yield :head %>
    <%#= turbo_include_tags %>
    <%#= stimulus_include_tags %>
  </head>

  <body class="bg-gray-50">
    <div class="h-12 bg-white shadow flex justify-center" style="outline: 1px solid red;">
      <div class="container flex" style="outline: 1px solid blue;">
        <div class="flex-grow">
          <% if current_user %>
            <%= current_user.email %>
          <% else %>
            <%= link_to 'Sign In', new_session_path(:user) %>
          <% end %>
        </div>
        <div class="flex-grow-0" id="test_count">
          <%= current_user.notifications.unread.count if current_user %>
        </div>
      </div>
    </div>

    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>